-- 建立 stock_history 表 (股票歷史)
CREATE TABLE IF NOT EXISTS stock_history (
    code TEXT NOT NULL,
    date_int BIGINT NOT NULL,
    open FLOAT,
    high FLOAT,
    low FLOAT,
    close FLOAT,
    volume BIGINT,
    amount FLOAT,
    foreign_buy BIGINT DEFAULT 0,
    trust_buy BIGINT DEFAULT 0,
    dealer_buy BIGINT DEFAULT 0,
    tdcc_count INTEGER DEFAULT 0,
    large_shareholder_pct FLOAT DEFAULT 0,
    date DATE,
    PRIMARY KEY (code, date_int)
);

-- 建立 institutional_investors 表 (法人買賣超)
CREATE TABLE IF NOT EXISTS institutional_investors (
    code TEXT NOT NULL,
    date_int BIGINT NOT NULL,
    foreign_net BIGINT DEFAULT 0,
    trust_net BIGINT DEFAULT 0,
    dealer_net BIGINT DEFAULT 0,
    date DATE,
    PRIMARY KEY (code, date_int)
);

-- 建立 stock_data 表 (每日行情快照)
CREATE TABLE IF NOT EXISTS stock_data (
    code TEXT NOT NULL,
    name TEXT,
    date DATE NOT NULL,
    open FLOAT,
    high FLOAT,
    low FLOAT,
    close FLOAT,
    volume BIGINT,
    PRIMARY KEY (code, date)
);

-- 建立 sync_status 表 (同步狀態)
CREATE TABLE IF NOT EXISTS sync_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_update TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 啟用 Row Level Security (RLS)
ALTER TABLE stock_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE institutional_investors ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE sync_status ENABLE ROW LEVEL SECURITY;

-- 建立開放讀取策略 (允許匿名讀取)
CREATE POLICY "Allow public read access" ON stock_history FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON institutional_investors FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON stock_data FOR SELECT USING (true);
CREATE POLICY "Allow public read access" ON sync_status FOR SELECT USING (true);

-- 建立服務端寫入策略 (僅允許 Service Role 寫入)
-- 注意: Service Role 預設繞過 RLS，所以不需要特別建立寫入策略，但為了明確性可以建立
-- 這裡我們只開放讀取，寫入依賴 Service Role Key
